
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "G:/progects_c++/cmakl/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
